auth_user.find (0.00) {'username': 'sys'}
django_session.save (0.00) {'_id': u'yuf8ll6tgxyaddyaapxfymogs6p6w8i2', 'expire_date': datetime.datetime(2018, 5, 27, 10, 52, 18, 680000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /favicon.ico
django_session.find (0.00) {'_id': 'yuf8ll6tgxyaddyaapxfymogs6p6w8i2', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 10, 52, 21, 234000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': u'5o0iapumgc7z6obis45uvzjsczdzhlz6', 'expire_date': datetime.datetime(2018, 5, 27, 10, 52, 21, 365000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': 'yuf8ll6tgxyaddyaapxfymogs6p6w8i2'}
django_session.remove (0.00) {'_id': {'$in': [u'yuf8ll6tgxyaddyaapxfymogs6p6w8i2']}}
auth_user.save (0.00) {'username': u'sys', 'first_name': u'', 'last_name': u'', '_id': ObjectId('5ae5cb53cddcb0354c11cf6a'), 'is_active': True, 'email': u'', 'is_superuser': True, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 13, 10, 52, 21, 371000, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$RM3mR6ar66t8$SRS3qPBkBP7FldCNOuunX0f1RK/YppeImlg2lVhOJZo=', 'date_joined': datetime.datetime(2018, 4, 29, 13, 40, 35, 764000, tzinfo=<UTC>)}
django_session.save (0.00) {'_id': u'5o0iapumgc7z6obis45uvzjsczdzhlz6', 'expire_date': datetime.datetime(2018, 5, 27, 10, 52, 21, 402000, tzinfo=<UTC>), 'session_data': u'MmU5YzEwYjExYTI3YTY2YmIwMGM0YmYwZWUwYmFkNmZjYzQyMzQ1OTp7Il9hdXRoX3VzZXJfYmFja2VuZCI6InBlcm1pc3Npb25fYmFja2VuZF9ub25yZWwuYmFja2VuZHMuTm9ucmVsUGVybWlzc2lvbkJhY2tlbmQiLCJfYXV0aF91c2VyX2lkIjoiNWFlNWNiNTNjZGRjYjAzNTRjMTFjZjZhIiwibGFuZ3VhZ2UiOiJlbiJ9'}
django_session.find (0.00) {'_id': '5o0iapumgc7z6obis45uvzjsczdzhlz6', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 10, 52, 21, 725000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '5o0iapumgc7z6obis45uvzjsczdzhlz6', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 10, 56, 4, 745000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.save (0.00) {'_id': u'3dsbu6gc9gomwobq1ctc3zee23uefm4g', 'expire_date': datetime.datetime(2018, 5, 27, 11, 43, 43, 679000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
Not Found: /favicon.ico
django_session.find (0.00) {'_id': '3dsbu6gc9gomwobq1ctc3zee23uefm4g', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 43, 46, 241000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'username': u'sys'}
django_session.save (0.00) {'_id': u'498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': datetime.datetime(2018, 5, 27, 11, 43, 46, 331000, tzinfo=<UTC>), 'session_data': u'YjAwMTViM2E0OTNjMDE0N2NjMTFiZjIxNzYzNmNkYTg5OGRiZGZjMzp7Imxhbmd1YWdlIjoiZW4ifQ=='}
django_session.find (0.00) {'_id': '3dsbu6gc9gomwobq1ctc3zee23uefm4g'}
django_session.remove (0.00) {'_id': {'$in': [u'3dsbu6gc9gomwobq1ctc3zee23uefm4g']}}
auth_user.save (0.00) {'username': u'sys', 'first_name': u'', 'last_name': u'', '_id': ObjectId('5ae5cb53cddcb0354c11cf6a'), 'is_active': True, 'email': u'', 'is_superuser': True, 'is_staff': False, 'last_login': datetime.datetime(2018, 5, 13, 11, 43, 46, 336000, tzinfo=<UTC>), 'password': u'pbkdf2_sha256$12000$RM3mR6ar66t8$SRS3qPBkBP7FldCNOuunX0f1RK/YppeImlg2lVhOJZo=', 'date_joined': datetime.datetime(2018, 4, 29, 13, 40, 35, 764000, tzinfo=<UTC>)}
django_session.save (0.00) {'_id': u'498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': datetime.datetime(2018, 5, 27, 11, 43, 46, 350000, tzinfo=<UTC>), 'session_data': u'MmU5YzEwYjExYTI3YTY2YmIwMGM0YmYwZWUwYmFkNmZjYzQyMzQ1OTp7Il9hdXRoX3VzZXJfYmFja2VuZCI6InBlcm1pc3Npb25fYmFja2VuZF9ub25yZWwuYmFja2VuZHMuTm9ucmVsUGVybWlzc2lvbkJhY2tlbmQiLCJfYXV0aF91c2VyX2lkIjoiNWFlNWNiNTNjZGRjYjAzNTRjMTFjZjZhIiwibGFuZ3VhZ2UiOiJlbiJ9'}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 43, 46, 370000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {'username': 'sys'}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 3, 528000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Not Found: /favicon.ico
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 12, 490000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 13, 895000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 15, 812000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 15, 977000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 23, 278000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 46, 23, 344000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 47, 42, 756000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 47, 42, 961000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 47, 42, 980000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 48, 21, 917000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 48, 22, 254000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 48, 22, 277000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 49, 6, 281000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 49, 6, 685000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 49, 6, 718000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 4, 44000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 4, 379000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 4, 397000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 20, 674000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 21, 77000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 21, 108000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 26, 793000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 26, 919000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Not Found: /hrm/sign_out
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 33, 307000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 39, 191000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 44, 630000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 44, 729000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 47, 771000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 47, 799000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 48, 879000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 48, 906000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 50, 392000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 50, 405000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 53, 298000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 50, 53, 318000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 51, 46, 91000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 51, 46, 445000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 51, 46, 468000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 20, 935000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 21, 493000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 21, 542000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 56, 918000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 59, 628000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 56, 59, 648000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 1, 841000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 1, 857000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 3, 53000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 3, 70000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 7, 88000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 9, 5000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 9, 19000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 10, 13000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 10, 26000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 10, 620000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 10, 634000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 12, 740000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 12, 753000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 15, 60000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 15, 73000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 16, 67000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 16, 80000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
auth_user.find (0.00) {}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 17, 476000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 57, 17, 489000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 2, 242000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 2, 664000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 2, 689000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 3, 793000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 3, 936000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 3, 953000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 9, 991000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 10, 346000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 12, 165000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 11, 58, 12, 192000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018/packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 12, 1, 7, 685000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 12, 1, 11, 687000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 12, 1, 14, 291000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 12, 1, 16, 415000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
django_session.find (0.00) {'_id': '498y9j49iucvhn6sbo16k36xgvbs6utt', 'expire_date': {'$gt': datetime.datetime(2018, 5, 13, 12, 1, 16, 780000, tzinfo=<UTC>)}}
auth_user.find (0.00) {'_id': ObjectId('5ae5cb53cddcb0354c11cf6a')}
Internal Server Error: /hrm/api
Traceback (most recent call last):
  File "E:\code\python\p2018\venv1\lib\site-packages\django\core\handlers\base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "E:\code\python\p2018\venv1\lib\site-packages\django\views\decorators\csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\code\python\p2018\packages\quicky\api.py", line 94, in call
    raise ex
Exception: import hrm.api.categories is error or not found
